### ISSUE TITLE
http://openspf.net -> http://www.open-spf.org/

### ISSUE THREAD

**Issue by firemdkfighter** [sdgathman/pyspf#21]
Please fix url for check spf record.
Domain http://openspf.net don't work.

**Comment by sdgathman** [comment]
That is an excellent restoration of the openspf.org,net domain!  Thank you.  I took a stab at it with https://spf.pymilter.org - but I think I should just redirect at this point.  What provision has been made for preventing another disappearance?

**Comment by k0ste** [comment]
I think actually users don't care what exactly service will be provide deny string. In deny string for MAILER-DAEMON provided useful url "why my domain not pass SPF checks", and this url currently don't work.

**Comment by sdgathman** [comment]
open-spf.org/why doesn't work with parameters.  

http://www.open-spf.org/Why/?sender=notifications@argentasoftware.com&ip=75.103.73.131

The little form also fails, of course.

**Comment by sdgathman** [comment]
What shall we use for email?  pyspf@open-spf.org doesn't work.  I could set up pyspf@pymilter.org, but maybe someone already has an appropriate email.

**Comment by stoecker** [comment]
P.S. Also adapt the README.

**Comment by sdgathman** [comment]
I updated openspf.net to open-spf.org.  I set the email to pyspf@pymilter.org.  I haven't set that up yet, but I plan to, and we are no worse off.
