### ISSUE TITLE
[Python3] SyntaxError at pydns.py

### ISSUE THREAD

**Issue by csuka** [sdgathman/pyspf#6]
````
➜  pyspf git:(master) ✗ python3 spf.py 1.2.3.4
Traceback (most recent call last):
  File "spf.py", line 95, in DNSLookup
    from SPF.pydns import DNSLookup
  File "/path/pyspf/SPF/pydns.py", line 28
    raise spf.TempError, 'DNS: TCP Fallback error: ' + str(x)
                       ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "spf.py", line 1886, in <module>
    print(q.dns_spf(argv[0]))
  File "spf.py", line 1086, in dns_spf
    a = [t for t in self.dns_txt(domain) if RE_SPF.match(t)]
  File "spf.py", line 1135, in dns_txt
    dns_list = self.dns(domainname, rr,ignore_void=ignore_void)
  File "spf.py", line 1266, in dns
    for k, v in DNSLookup(name, qtype, self.strict, timeout):
  File "spf.py", line 97, in DNSLookup
    from SPF.dnspython import DNSLookup
  File "/path/pyspf/SPF/dnspython.py", line 27
    except dns.exception.DNSException,x:
                                     ^
SyntaxError: invalid syntax
````

Changed: ``raise spf.AmbiguityWarning, 'DNS: Truncated UDP Reply, SPF records should fit in a UDP packet, retrying TCP'``

To 
``raise spf.AmbiguityWarning('DNS: Truncated UDP Reply, SPF records should fit in a UDP packet, retrying TCP')
``

To make it work on python3 on my setup.

**Comment by sdgathman** [comment]
The real issue here is that the true "master" branch is pyspf-2_0-branch.  This is an artifact of converting from CVS.  I apologize for being such a git newbie, but I still haven't managed to get the branches renamed.  I did make a pyspf-2.1 branch that was a copy of master - but I'm not sure what the next step is.  I guess I should make a note of the situation in the README on the current "master".

**Comment by sdgathman** [comment]
I tried that.  Notice the "merge pyspy-2_0-branch into master" commit - but I managed to screw it up.  Fortunately, I saved master beforehand as the pyspf-2.1 branch.
